android {
    namespace = "me.aap.fermata.engine.exoplayer"
    defaultConfig {
        versionCode 1
        versionName "1.0"
    }

    ext.addons = [
            [
                    name       : 'exoplayer',
                    class      : 'me.aap.fermata.engine.exoplayer.ExoPlayerAddon',
                    icon       : 'ic_launcher_foreground',
                    depends    : '',
                    enabled    : true,
                    displayName: '@string/engine_exo_name',
                    order      : 0,
                    hasSettings: true
            ]
    ]
}

dependencies {
    implementation project(':utils')
    implementation project(':fermata')
    implementation "androidx.media:media:${ANDROIDX_MEDIA_VERSION}"
    implementation("androidx.media3:media3-exoplayer:1.8.0")
    implementation("androidx.media3:media3-exoplayer-hls:1.8.0")
    implementation("androidx.media3:media3-exoplayer-dash:1.8.0")
    implementation("androidx.media3:media3-datasource-cronet:1.8.0")
    implementation("androidx.media3:media3-transformer:1.8.0")
}
